# Generated by Django 2.2.1 on 2019-06-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
