# Generated by Django 2.2.1 on 2019-06-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginapp', '0002_auto_20190603_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='password2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='first_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
